version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      - "8085:80"
    depends_on:
      backend-us:
        condition: service_healthy
      backend-eu:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-us:
    image: postgres:14
    container_name: postgres_us
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-properties_db}
    volumes:
      - ./seeds/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./seeds/seed_us.sql:/docker-entrypoint-initdb.d/2-seed.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-properties_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-eu:
    image: postgres:14
    container_name: postgres_eu
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-properties_db}
    volumes:
      - ./seeds/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./seeds/seed_eu.sql:/docker-entrypoint-initdb.d/2-seed.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-properties_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-us:
    build: ./backend
    container_name: node_backend_us
    environment:
      - REGION=us
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db-us:5432/${DB_NAME:-properties_db}
      - KAFKA_BROKER=kafka:29092
      - PORT=8000
    depends_on:
      db-us:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8000/us/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8001:8000"

  backend-eu:
    build: ./backend
    container_name: node_backend_eu
    environment:
      - REGION=eu
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db-eu:5432/${DB_NAME:-properties_db}
      - KAFKA_BROKER=kafka:29092
      - PORT=8000
    depends_on:
      db-eu:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8000/eu/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8002:8000"
